export const route = {
  login: "/",
  dashboard: "/dashboard",
  userManagement: "/user-Management",
  addUser: "/user-Management/admin/add",
  viewRecycler: (id) => `/user-Management/view-recycler/${id}`,
  viewRecyclerItems: `/user-Management/view-recycler-items`,
  viewCollector: (id) => `/user-Management/view-collector/${id}`,
  editPermission: (role) => `/user-Management/edit-permission/${role}`,
  appContentManagement: "/app-content-Management",
  addWaste: "/app-content-Management/add-waste",
  addGuidelines: "/app-content-Management/add-Guidelines",
  collectionManagement: "/collection-Management",
  rewardsManagement: "/rewards-Management",
  createCampaign: "/create-campaign",
  collectorServiceManagement: "/Collector-Service-Management",
  viewCollecterServiceInformation:
    "/Collector-Service-Management/Collecter-Information",
  NotFoundPage: "/not-found",
};
